### ISSUE TITLE
Error: Cannot find module '../utilities/DAG'

### ISSUE THREAD

**Issue by titov-andrei** [wejs/we-admin-blog#1]
`module.js:471
    throw err;
    ^

Error: Cannot find module '../utilities/DAG'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/andrew/CODE/JS/GIT/we-admin-blog/node_modules/ember-cli/lib/models/addons-factory.js:8:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
`

**Comment by albertosouza** [comment]
Hi @titov-andrei , thanks for your feedback.

I fixed the README.md and added right install instructions: https://github.com/wejs/we-admin-blog/blob/master/README.md

And you can see how its works with we.js generator: https://github.com/wejs/generator-wejs#generate-one-wejs-blog-project

And if this not fix this error, please send other feedback.
